import {
  burgerking,
  crepefactory,
  farmRanchPizza,
  campAbdelmoula,
  instagram,
  twitter,
  facebook,
  linkedin,
  crepe1,
  crepe2,
  crepe3,
  crepe4,
} from "../assets";
export const items = [
  {
    id: "1",
    title: "Burger king",
    logo: burgerking,
    rate: "9.9",
    type: "Restaurant",
    address: "Résidence du printemps El mourouj 5, 2074",
  },
  {
    id: "2",
    title: "Crepe Factory",
    logo: crepefactory,
    rate: "9.8",
    type: "Creperie",
    address: "Ibn Abi Sofien, 15 bis Rue Mouawiya Ibn Abi Sofiene, Ariana 2080",
  },
  {
    id: "3",
    title: "Farm Ranch",
    logo: farmRanchPizza,
    rate: "9.0",
    type: "Pizzaria",
    address:
      "49 Residance el Kods, Avenue Hedi Nouira, Ennasr 2 Ennasr 2، 2037",
  },
  {
    id: "4",
    title: "Camp Adelmoula",
    logo: campAbdelmoula,
    rate: "9.8",
    type: "Camp",
    address: "Tembaine",
  },
  {
    id: "5",
    title: "Burger king",
    logo: burgerking,
    rate: "9.9",
    type: "Restaurant",
    address: "Résidence du printemps El mourouj 5, 2074",
  },
  // {
  //   id: "6",
  //   title: "Crepe Factory",
  //   logo: crepefactory,
  //   rate: "9.8",
  //   type: "Creperie",
  //   address: "Ibn Abi Sofien, 15 bis Rue Mouawiya Ibn Abi Sofiene, Ariana 2080",
  // },
  // {
  //   id: "7",
  //   title: "Farm Ranch",
  //   logo: farmRanchPizza,
  //   rate: "9.0",
  //   type: "Pizzaria",
  //   address:
  //     "49 Residance el Kods, Avenue Hedi Nouira, Ennasr 2 Ennasr 2، 2037",
  // },
  // {
  //   id: "8",
  //   title: "Camp Adelmoula",
  //   logo: campAbdelmoula,
  //   rate: "9.8",
  //   type: "Camp",
  //   address: "Tembaine",
  // },
  // {
  //   id: "9",
  //   title: "Burger king",
  //   logo: burgerking,
  //   rate: "9.9",
  //   type: "Restaurant",
  //   address: "Résidence du printemps El mourouj 5, 2074",
  // },
  // {
  //   id: "10",
  //   title: "Crepe Factory",
  //   logo: crepefactory,
  //   rate: "9.8",
  //   type: "Creperie",
  //   address: "Ibn Abi Sofien, 15 bis Rue Mouawiya Ibn Abi Sofiene, Ariana 2080",
  // },
  // {
  //   id: "11",
  //   title: "Farm Ranch",
  //   logo: farmRanchPizza,
  //   rate: "9.0",
  //   type: "Pizzaria",
  //   address:
  //     "49 Residance el Kods, Avenue Hedi Nouira, Ennasr 2 Ennasr 2، 2037",
  // },
  // {
  //   id: "12",
  //   title: "Camp Adelmoula",
  //   logo: campAbdelmoula,
  //   rate: "9.8",
  //   type: "Camp",
  //   address: "Tembaine",
  // },
  // {
  //   id: "14",
  //   title: "Crepe Factory",
  //   logo: crepefactory,
  //   rate: "9.8",
  //   type: "Creperie",
  //   address: "Ibn Abi Sofien, 15 bis Rue Mouawiya Ibn Abi Sofiene, Ariana 2080",
  // },
  // {
  //   id: "15",
  //   title: "Farm Ranch",
  //   logo: farmRanchPizza,
  //   rate: "9.0",
  //   type: "Pizzaria",
  //   address:
  //     "49 Residance el Kods, Avenue Hedi Nouira, Ennasr 2 Ennasr 2، 2037",
  // },
  // {
  //   id: "16",
  //   title: "Camp Adelmoula",
  //   logo: campAbdelmoula,
  //   rate: "9.8",
  //   type: "Camp",
  //   address: "Tembaine",
  // },
];
export const socialMedia = [
  {
    id: "social-media-1",
    icon: instagram,
    link: "https://www.instagram.com/",
  },
  {
    id: "social-media-2",
    icon: facebook,
    link: "https://www.facebook.com/",
  },
  {
    id: "social-media-3",
    icon: twitter,
    link: "https://www.twitter.com/",
  },
  {
    id: "social-media-4",
    icon: linkedin,
    link: "https://www.linkedin.com/",
  },
];
export const categories = [
  { value: "1", label: "Restaurant" },
  { value: "2", label: "Hotel" },
  { value: "3", label: "Coffee" },
  { value: "4", label: "Camp" },
];
export const options = [
  { value: "Tunis", label: "Tunis" },
  { value: "Ariana", label: "Ariana" },
  { value: "BenArous", label: "Ben Arous" },
  { value: "Bizerte", label: "Bizerte" },
  { value: "Gabes", label: "Gabes" },
  { value: "Gafsa", label: "Gafsa" },
  { value: "Jendouba", label: "Jendouba" },
  { value: "Kairouan", label: "Kairouan" },
  { value: "Kasserine", label: "Kasserine" },
  { value: "Kebili", label: "Kebili" },
  { value: "Mahdia", label: "Mahdia" },
  { value: "Manouba", label: "Manouba" },
  { value: "Medenine", label: "Medenine" },
  { value: "Monastir", label: "Monastir" },
  { value: "Nabeul", label: "Nabeul" },
  { value: "Sfax", label: "Sfax" },
  { value: "SidiBouzid", label: "Sidi Bouzid" },
  { value: "Siliana", label: "Siliana" },
  { value: "Sousse", label: "Sousse" },
  { value: "Tataouine", label: "Tataouine" },
  { value: "Tozeur", label: "Tozeur" },
  { value: "Zaghouan", label: "Zaghouan" },
];
export const Tunis = [
  { value: "Tunis", label: "Tunis" },
  { value: "Ariana", label: "Ariana" },
  { value: "Ben Arous", label: "Ben Arous" },
  { value: "Manouba", label: "Manouba" },
];
export const Ariana = [
  { value: "Ariana", label: "Ariana" },
  { value: "La Soukra", label: "La Soukra" },
  { value: "Raoued", label: "Raoued" },
  { value: "Sidi Thabet", label: "Sidi Thabet" },
];
export const BenArous = [
  { value: "Ben Arous", label: "Ben Arous" },
  { value: "El Mourouj", label: "El Mourouj" },
  { value: "Ezzahra", label: "Ezzahra" },
  { value: "Fouchana", label: "Fouchana" },
  { value: "Hammam Chott", label: "Hammam Chott" },
  { value: "Hammam Lif", label: "Hammam Lif" },
  { value: "Mohamedia", label: "Mohamedia" },
  { value: "Mornag", label: "Mornag" },
  { value: "Radès", label: "Radès" },
];
export const Bizerte = [
  { value: "Bizerte", label: "Bizerte" },
  { value: "El Alia", label: "El Alia" },
  { value: "Ghar El Melh", label: "Ghar El Melh" },
  { value: "Mateur", label: "Mateur" },
  { value: "Menzel Bourguiba", label: "Menzel Bourguiba" },
  { value: "Ras Jebel", label: "Ras Jebel" },
  { value: "Sejnane", label: "Sejnane" },
  { value: "Tinja", label: "Tinja" },
  { value: "Utique", label: "Utique" },
  { value: "Zarzouna", label: "Zarzouna" },
];
export const Gabes = [
  { value: "Gabes", label: "Gabes" },
  { value: "El Hamma", label: "El Hamma" },
  { value: "Mareth", label: "Mareth" },
  { value: "Matmata", label: "Matmata" },
  { value: "Menzel Habib", label: "Menzel Habib" },
  { value: "Oudhref", label: "Oudhref" },
];
export const Gafsa = [
  { value: "Gafsa", label: "Gafsa" },
  { value: "El Ksar", label: "El Ksar" },
  { value: "El Guettar", label: "El Guettar" },
  { value: "Métlaoui", label: "Métlaoui" },
  { value: "Redeyef", label: "Redeyef" },
  { value: "Moularès", label: "Moularès" },
  { value: "Sened", label: "Sened" },
  { value: "Sidi Aïch", label: "Sidi Aïch" },
];
export const Jendouba = [
  { value: "Jendouba", label: "Jendouba" },
  { value: "Aïn Draham", label: "Aïn Draham" },
  { value: "Bou Salem", label: "Bou Salem" },
  { value: "Fernana", label: "Fernana" },
  { value: "Ghardimaou", label: "Ghardimaou" },
  { value: "Jendouba Nord", label: "Jendouba Nord" },
  { value: "Jendouba Sud", label: "Jendouba Sud" },
  { value: "Oued Meliz", label: "Oued Meliz" },
];
export const Kairouan = [
  { value: "Bou Hajla", label: "Bou Hajla" },
  { value: "Chebika", label: "Chebika" },
  { value: "Echrarda", label: "Echrarda" },
  { value: "Haffouz", label: "Haffouz" },
  { value: "Hajeb El Ayoun", label: "Hajeb El Ayoun" },
  { value: "Kairouan Nord", label: "Kairouan Nord" },
  { value: "Kairouan Sud", label: "Kairouan Sud" },
  { value: "Nasrallah", label: "Nasrallah" },
  { value: "Oueslatia", label: "Oueslatia" },
  { value: "Sbikha", label: "Sbikha" },
  { value: "Sbeitla", label: "Sbeitla" },
  { value: "Sbiba", label: "Sbiba" },
  { value: "Chrarda", label: "Chrarda" },
];
export const Kasserine = [
  { value: "Feriana", label: "Feriana" },
  { value: "Hassi El Ferid", label: "Hassi El Ferid" },
  { value: "Hidra", label: "Hidra" },
  { value: "Jedelienne", label: "Jedelienne" },
  { value: "Foussana", label: "Foussana" },
  { value: "Foussana Nord", label: "Foussana Nord" },
  { value: "Foussana Sud", label: "Foussana Sud" },
  { value: "Haïdra Nord", label: "Haïdra Nord" },
  { value: "Haïdra Sud", label: "Haïdra Sud" },
  { value: "Hassi El Ferid Nord", label: "Hassi El Ferid Nord" },
  { value: "Hassi El Ferid Sud", label: "Hassi El Ferid Sud" },
  { value: "Jedelienne Nord", label: "Jedelienne Nord" },
  { value: "Jedelienne Sud", label: "Jedelienne Sud" },
  { value: "Kasserine Nord", label: "Kasserine Nord" },
  { value: "Kasserine Sud", label: "Kasserine Sud" },
  { value: "Sbeitla", label: "Sbeitla" },
  { value: "Sbiba", label: "Sbiba" },
  { value: "Thala", label: "Thala" },
];
export const Kebili = [
  { value: "Douz", label: "Douz" },
  { value: "Faouar", label: "Faouar" },
  { value: "Kebili Nord", label: "Kebili Nord" },
  { value: "Kebili Sud", label: "Kebili Sud" },
  { value: "Souk Lahad", label: "Souk Lahad" },
];
export const Mahdia = [
  { value: "Boumerdès", label: "Boumerdès" },
  { value: "Chebba", label: "Chebba" },
  { value: "Chorbane", label: "Chorbane" },
  { value: "El Jem", label: "El Jem" },
  { value: "Essouassi", label: "Essouassi" },
  { value: "Hebira", label: "Hebira" },
  { value: "Karkar", label: "Karkar" },
  { value: "Ksour Essef", label: "Ksour Essef" },
  { value: "Mahdia", label: "Mahdia" },
  { value: "Melloulèche", label: "Melloulèche" },
  { value: "Ouled Chamekh", label: "Ouled Chamekh" },
  { value: "Rejiche", label: "Rejiche" },
  { value: "Sidi Alouane", label: "Sidi Alouane" },
  { value: "Sidi Zid", label: "Sidi Zid" },
  { value: "Tlelsa", label: "Tlelsa" },
];
export const Manouba = [
  { value: "Mornag", label: "Mornag" },
  { value: "Manouba", label: "Manouba" },
  { value: "Douar Hicher", label: "Douar Hicher" },
  { value: "Oued Ellil", label: "Oued Ellil" },
  { value: "Borj El Amri", label: "Borj El Amri" },
  { value: "El Battan", label: "El Battan" },
  { value: "Djedeida", label: "Djedeida" },
  { value: "Tebourba", label: "Tebourba" },
];
export const Medenine = [
  { value: "Medenine", label: "Medenine" },
  { value: "Ben Gardane", label: "Ben Gardane" },
  { value: "Djerba", label: "Djerba" },
  { value: "Zarzis", label: "Zarzis" },
  { value: "Tataouine", label: "Tataouine" },
  { value: "Kebili", label: "Kebili" },
];
export const Monastir = [
  { value: "Monastir", label: "Monastir" },
  { value: "Sahline", label: "Sahline" },
  { value: "Bembla", label: "Bembla" },
  { value: "Moknine", label: "Moknine" },
  { value: "Khniss", label: "Khniss" },
  { value: "Jemmal", label: "Jemmal" },
  { value: "Beni Hassen", label: "Beni Hassen" },
  { value: "Zeramdine", label: "Zeramdine" },
  { value: "Ouerdanine", label: "Ouerdanine" },
  { value: "Ksibet el-Médiouni", label: "Ksibet el-Médiouni" },
  { value: "Téboulba", label: "Téboulba" },
  { value: "Sayada-Lamta-Bou Hajar", label: "Sayada-Lamta-Bou Hajar" },
];
export const Nabeul = [
  { value: "Nabeul", label: "Nabeul" },
  { value: "Beni Khalled", label: "Beni Khalled" },
  { value: "Beni Khiar", label: "Beni Khiar" },
  { value: "Bou Argoub", label: "Bou Argoub" },
  { value: "Dar Chaaban", label: "Dar Chaaban" },
  { value: "El Haouaria", label: "El Haouaria" },
  { value: "El Mida", label: "El Mida" },
  { value: "Grombalia", label: "Grombalia" },
  { value: "Hammam Ghezèze", label: "Hammam Ghezèze" },
  { value: "Hammamet", label: "Hammamet" },
  { value: "Kelibia", label: "Kelibia" },
  { value: "Korba", label: "Korba" },
  { value: "Menzel Bouzelfa", label: "Menzel Bouzelfa" },
  { value: "Menzel Horr", label: "Menzel Horr" },
  { value: "Menzel Temime", label: "Menzel Temime" },
  { value: "Nabeul Medina", label: "Nabeul Medina" },
  { value: "Soliman", label: "Soliman" },
  { value: "Takelsa", label: "Takelsa" },
  { value: "Tazarka", label: "Tazarka" },
  { value: "Zaouiet Djedidi", label: "Zaouiet Djedidi" },
];
export const Sfax = [
  { value: "Sfax", label: "Sfax" },
  { value: "Agareb", label: "Agareb" },
  { value: "Bir Ali Ben Khalifa", label: "Bir Ali Ben Khalifa" },
  { value: "El Amra", label: "El Amra" },
  { value: "El Hencha", label: "El Hencha" },
  { value: "Ghraiba", label: "Ghraiba" },
  { value: "Jebiniana", label: "Jebiniana" },
  { value: "Kerkennah", label: "Kerkennah" },
  { value: "Mahares", label: "Mahares" },
  { value: "Menzel Chaker", label: "Menzel Chaker" },
  { value: "Sakiet Eddaier", label: "Sakiet Eddaier" },
  { value: "Sakiet Ezzit", label: "Sakiet Ezzit" },
  { value: "Sfax Medina", label: "Sfax Medina" },
  { value: "Sfax West", label: "Sfax West" },
  { value: "Skhira", label: "Skhira" },
  { value: "Thyna", label: "Thyna" },
];
export const SidiBouzid = [
  { value: "Sidi Bouzid", label: "Sidi Bouzid" },
  { value: "Jilma", label: "Jilma" },
  { value: "Cebbala Ouled Asker", label: "Cebbala Ouled Asker" },
  { value: "Menzel Bouzaiane", label: "Menzel Bouzaiane" },
  { value: "Meknassy", label: "Meknassy" },
  { value: "Regueb", label: "Regueb" },
  { value: "Sidi Ali Ben Aoun", label: "Sidi Ali Ben Aoun" },
  { value: "Souk Jedid", label: "Souk Jedid" },
];
export const Siliana = [
  { value: "Bouarada", label: "Bouarada" },
  { value: "El Aroussa", label: "El Aroussa" },
  { value: "Gaafour", label: "Gaafour" },
  { value: "Kesra", label: "Kesra" },
  { value: "Makthar", label: "Makthar" },
  { value: "Rouhia", label: "Rouhia" },
  { value: "Sidi Bou Rouis", label: "Sidi Bou Rouis" },
  { value: "Siliana", label: "Siliana" },
  { value: "Teboursouk", label: "Teboursouk" },
  { value: "Bargou", label: "Bargou" },
];
export const Sousse = [
  { value: "Sousse", label: "Sousse" },
  { value: "Hammam Sousse", label: "Hammam Sousse" },
  { value: "Kalaa Kebira", label: "Kalaa Kebira" },
  { value: "Kalaa Seghira", label: "Kalaa Seghira" },
  { value: "Kondar", label: "Kondar" },
  { value: "Msaken", label: "Msaken" },
  { value: "Enfidha", label: "Enfidha" },
  { value: "Bouficha", label: "Bouficha" },
  { value: "Akouda", label: "Akouda" },
  { value: "Hergla", label: "Hergla" },
  { value: "Sidi Bou Ali", label: "Sidi Bou Ali" },
  { value: "Sidi El Heni", label: "Sidi El Heni" },
  { value: "Zaouia Ksiba Thrayet", label: "Zaouia Ksiba Thrayet" },
];
export const Tataouine = [
  { value: "Bir Lahmar", label: "Bir Lahmar" },
  { value: "Dehiba", label: "Dehiba" },
  { value: "Ghomrassen", label: "Ghomrassen" },
  { value: "Remada", label: "Remada" },
  { value: "Tataouine Nord", label: "Tataouine Nord" },
  { value: "Tataouine Sud", label: "Tataouine Sud" },
];
export const Tozeur = [
  { value: "Degache", label: "Degache" },
  { value: "Hazoua", label: "Hazoua" },
  { value: "Nefta", label: "Nefta" },
  { value: "Tameghza", label: "Tameghza" },
  { value: "Tozeur", label: "Tozeur" },
];
export const Zaghouan = [
  { value: "El Fahs", label: "El Fahs" },
  { value: "Nadhour", label: "Nadhour" },
  { value: "Zaghouan", label: "Zaghouan" },
];
export const regions = [
  { value: "Tunis", table: { Tunis } },
  { value: "Ariana", table: { Ariana } },
  { value: "BenArous", table: { BenArous } },
  { value: "Bizerte", table: { Bizerte } },
  { value: "Gabes", table: { Gabes } },
  { value: "Gafsa", table: { Gafsa } },
  { value: "Jendouba", table: { Jendouba } },
  { value: "Kairouan", table: { Kairouan } },
  { value: "Kasserine", table: { Kasserine } },
  { value: "Kebili", table: { Kebili } },
  { value: "Mahdia", table: { Mahdia } },
  { value: "Manouba", table: { Manouba } },
  { value: "Medenine", table: { Medenine } },
  { value: "Monastir", table: { Monastir } },
  { value: "Nabeul", table: { Nabeul } },
  { value: "Sfax", table: { Sfax } },
  { value: "SidiBouzid", table: { SidiBouzid } },
  { value: "Siliana", table: { Siliana } },
  { value: "Sousse", table: { Sousse } },
  { value: "Tataouine", table: { Tataouine } },
  { value: "Tozeur", table: { Tozeur } },
  { value: "Zaghouan", table: { Zaghouan } },
];
export const photos = [crepe1, crepe2, crepe3, crepe4];
